version: '3'
services:
  app:
    image: 'msc-test-image'
    command: python3 job.py
    volumes:
      - .:/app
    environment:
      - STOCK_NAME=BTCUSD_1h_full
      - REPLAY_CAPACITY=1e4
      - GAMMA=0.99
      - BATCH_SIZE=4096
      - NN_ARCHITECTURE=(128, 128)
      - NN_ACTIVATION=relu
      - NN_LEARNING_RATE=0.0001
      - NN_L2_REG=0.0001
      - NN_OPTIMIZER=Adam
      - NN_TAU=20
      - MODEL=Double Deep Q-Learning Network
      - COMMENT=An agent to learn how to negotiate stocks
      - TRAIN_EPISODES=100
      - EPISODE_STEPS=240
      - INITIAL_BALANCE=1000